name: Repo Sync

on:
  push:
    branches:
    - default
    paths:
    - .github/workflows/**
  schedule:
  - cron: '45 1 * * *'

jobs:
  graal-master:
    name: Keep graal/master in sync with upstream master
    runs-on: ubuntu-latest
    steps:
    - name: Checkout graal/master branch
      uses: actions/checkout@v2
      with:
        ref: graal/master
        fetch-depth: 0
    - name: Sync branch
      run: |
        git config --local user.email "fzakkak@redhat.com"
        git config --local user.name "Foivos Zakkak through GH action"
        git remote add upstream https://github.com/oracle/graal
        git fetch upstream master
        git merge --ff-only upstream/master
        git push --quiet origin graal/master
  mandrel-master:
    name: Keep master in sync with default
    runs-on: ubuntu-latest
    steps:
    - name: Checkout graal/master branch
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Sync branch
      run: |
        git config --local user.email "fzakkak@redhat.com"
        git config --local user.name "Foivos Zakkak through GH action"
        git fetch origin default
        git merge --ff-only origin/default
        git push --quiet origin master
