name: Weekly CI

on:
  push:
    paths:
      - '.github/workflows/weekly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
  pull_request:
    paths:
      - '.github/workflows/weekly.yml'
      - '.github/workflows/base.yml'
      - '.github/workflows/base-windows.yml'
  schedule:
    - cron: '15 0 * * 6'
  workflow_dispatch:

# The following aims to reduce CI CPU cycles by:
# 1. Cancelling any previous builds of this PR when pushing new changes to it
# 2. Cancelling any previous builds of a branch when pushing new changes to it in a fork
# 3. Cancelling any pending builds, but not active ones, when pushing to a branch in the main
#    repository. This prevents us from constantly cancelling CI runs, while being able to skip
#    intermediate builds. E.g., if we perform two pushes the first one will start a CI job and
#    the second one will add another one to the queue; if we perform a third push while the
#    first CI job is still running the previously queued CI job (for the second push) will be
#    cancelled and a new CI job will be queued for the latest (third) push.
concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'graalvm/mandrel' }}

jobs:
  ####
  # Test Mandrel with JDK 22
  ####
  q-main-mandrel-jdk-22:
    name: "Q main M latest JDK 22"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      jdk: "22/ea"
      issue-number: "580"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "208"
      build-stats-tag: "gha-linux-qmain-mlatest-jdk22ea"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  q-main-mandrel-jdk-22-win:
    name: "Q main M latest JDK 22 windows"
    uses: graalvm/mandrel/.github/workflows/base-windows.yml@default
    with:
      quarkus-version: "main"
      version: "graal/master"
      jdk: "22/ea"
      issue-number: "579"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "207"
      build-stats-tag: "gha-win-qmain-mlatest-jdk22ea"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Mandrel 23.1 with JDK 21
  ####
  q-main-mandrel-23_1:
    name: "Q main M 23.1"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      version: "mandrel/23.1"
      jdk: "21/ea"
      issue-number: "563"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "198"
      build-stats-tag: "gha-linux-qmain-m23_1-jdk21ea"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  q-main-mandrel-23_1-win:
    name: "Q main M 23.1 windows"
    uses: graalvm/mandrel/.github/workflows/base-windows.yml@default
    with:
      quarkus-version: "main"
      version: "mandrel/23.1"
      jdk: "21/ea"
      issue-number: "562"
      issue-repo: "graalvm/mandrel"
      mandrel-it-issue-number: "199"
      build-stats-tag: "gha-win-qmain-m23_1-jdk21ea"
    secrets:
      ISSUE_BOT_TOKEN: ${{ secrets.MANDREL_BOT_TOKEN }}
      UPLOAD_COLLECTOR_TOKEN: ${{ secrets.UPLOAD_COLLECTOR_TOKEN }}
  ####
  # Test Quarkus 3.2 with 23_0 quayio images
  ####
  q-3_2-mandrel-23_0-quayio:
    name: "Q 3.2 M 23.0 image"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "3.2.0.Final"
      builder-image: "quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17"
  ####
  # Test Quarkus 2.13 with 22_3 quayio images
  ####
  q-2_13-mandrel-22_3-quayio:
    name: "Q 2.13 M 22.3 image"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "2.13.8.Final"
      builder-image: "quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17"
  q-main-mandrel-22_3-quayio:
    name: "Q main M 22.3 image"
    uses: graalvm/mandrel/.github/workflows/base.yml@default
    with:
      quarkus-version: "main"
      builder-image: "quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17"
